### ISSUE TITLE
Urgent. App now crashes canot find map platform for maps

### ISSUE THREAD

**Issue by chitgoks** [SupasinTatiyanupanwong/map-kit-android#13]
Did the method in google maps platform change perhaps in the new maps?
keeps crashing because of this

```
  Process: org.droidgox.phivolcs, PID: 9109
java.lang.RuntimeException: Unable to get provider dev.supasintatiyanupanwong.libraries.android.kits.maps.MapKitInitProvider: java.lang.IllegalStateException: Can't find supported platform, make sure to include one of the next artifacts: ':maps-amazon', ':maps-google', or ':maps-huawei'
at android.app.ActivityThread.installProvider(ActivityThread.java:8173)
at android.app.ActivityThread.installContentProviders(ActivityThread.java:7709)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7573)
at android.app.ActivityThread.access$2600(ActivityThread.java:260)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2435)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:219)
at android.app.ActivityThread.main(ActivityThread.java:8668)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
Caused by: java.lang.IllegalStateException: Can't find supported platform, make sure to include one of the next artifacts: ':maps-amazon', ':maps-google', or ':maps-huawei'
at dev.supasintatiyanupanwong.libraries.android.kits.maps.MapsPlatform.findPlatform(MapsPlatform.java:68)
at dev.supasintatiyanupanwong.libraries.android.kits.maps.MapsPlatform.init(MapsPlatform.java:39)
at dev.supasintatiyanupanwong.libraries.android.kits.maps.MapKitInitProvider.attachInfo(MapKitInitProvider.java:34)
at android.app.ActivityThread.installProvider(ActivityThread.java:8168)
at android.app.ActivityThread.installContentProviders(ActivityThread.java:7709) 
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7573) 
at android.app.ActivityThread.access$2600(ActivityThread.java:260) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2435) 
at android.os.Handler.dispatchMessage(Handler.java:110) 
at android.os.Looper.loop(Looper.java:219) 
at android.app.ActivityThread.main(ActivityThread.java:8668) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109) 
```

**Comment by chitgoks** [comment]
closing. i used a new environment and the default flavor used was amazon which i do not have. my bad.
