### ISSUE TITLE
Error inflating class fragment

### ISSUE THREAD

**Issue by chitgoks** [SupasinTatiyanupanwong/map-kit-android#14]
Fatal Exception: android.view.InflateException: Binary XML file line #18: Error inflating class fragment
```
Fatal Exception: android.view.InflateException: Binary XML file line #18: Error inflating class fragment
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at dev.supasintatiyanupanwong.libraries.android.kits.maps.MapFragment.onCreateView(MapFragment.java:73)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
       at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:3086)
       at androidx.fragment.app.Fragment.performResume(Fragment.java:3048)
       at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:607)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:306)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
       at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:3086)
       at androidx.fragment.app.Fragment.performResume(Fragment.java:3048)
       at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:607)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:306)
       at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java:745)
       at androidx.fragment.app.SpecialEffectsController$Operation.completeSpecialEffect(SpecialEffectsController.java:672)
       at androidx.fragment.app.DefaultSpecialEffectsController$SpecialEffectsInfo.completeSpecialEffect(DefaultSpecialEffectsController.java)
       at androidx.fragment.app.DefaultSpecialEffectsController$2.onAnimationEnd(DefaultSpecialEffectsController.java:190)
       at android.animation.AnimatorSet$AnimatorSetListener.onAnimationEnd(AnimatorSet.java:818)
       at android.animation.AnimatorSet$AnimatorSetListener.onAnimationEnd(AnimatorSet.java:818)
       at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1056)
       at android.animation.ValueAnimator.access$400(ValueAnimator.java:50)
       at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:644)
       at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:660)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
       at android.view.Choreographer.doCallbacks(Choreographer.java:591)
       at android.view.Choreographer.doFrame(Choreographer.java:559)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5292)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by SupasinTatiyanupanwong** [comment]
Can you please give me more context?  Maybe some sample that causing this problem?

**Comment by chitgoks** [comment]
I will just close this. i only got this crash log from crashlytics. sorry.

**Comment by SupasinTatiyanupanwong** [comment]
Nevermind. Feels free to reopen this if this starting to become an issue and/or can reproduce.
